### ISSUE TITLE
need to setup a sharelatex project 

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/HDP_TSE#1]
Dr.menzies, @timm, please set up the share latex for HDP TSE paper.

JC account is jc@lifove.net

**Comment by timm** [comment]
sharelatex is barphing when i try to connect it here. remind me to try in a few hours

![image](https://cloud.githubusercontent.com/assets/29195/9853989/7a50c9aa-5ad4-11e5-9436-e30847387bc3.png)

**Comment by WeiFoo** [comment]
REMINDER,@timm please setup share latex!

**Comment by timm** [comment]
i think this is working now

close this issue if "yes"
